version: '3'

services:
    db:
        image: mysql:8.0.31
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3307:3307"
        volumes:
            - ./db/mysql/volumes:/var/lib/mysql

    web:
        build: ./communication-core-connection
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
        volumes:
            - .:/myapp
            - gem_data:/usr/local/bundle
        ports:
            - 3001:3001
        depends_on:
            - db 
        tty: true
        stdin_open: true

volumes:
  gem_data: